window.addEventListener('load', function () {
  // The page is fully loaded

  const assignments = document.querySelectorAll("div.upcoming-event.course-event a");

  

  // Fetching JSON Data from local API
  fetch('http://127.0.0.1:3000/receive')
    .then((res) => {
      return res.json();
    })
    .then((data) => {

      // Creating an empty array for the completed assignment ID's to go into
      completedId = [];

      assignments.forEach(assignment => {

        // For each assignment a relative URL is generated, and if the relative includes the word "assignment" then it moves on.
        let relURL = assignment.pathname;

        if (relURL.includes('assignment')) {

          // Then, an "assignmentId" is generated by stripping the id from the relative URL generated earlier.
          const assignmentId = Number(relURL.split('/')[2]);

          // Then, another foreach is nested, and it loops through the array of data that is provided by the fetch.
          data.forEach(obj => {

            // Each object from the data array is checked to see if it matches with any of the assignments on the home page of Schoology. If it finds a match it pushes it into completedId array.
            if (obj.id === assignmentId) {

              completedId.push(assignmentId);

            }

          })

        }

      })

      // The completedId array is then looped over, it uses the ID to select each individual element
      // and then add a check mark right next to it

      completedId.forEach(id => {

        const element = document.querySelector(`a[href="/assignment/${id}"]`);

        let span = document.createElement('span');

        span.innerHTML = '✔'

        element.parentNode.insertBefore(span, element.nextSibling);

      })

    })

})